# Generated by Django 5.2.16 on 2026-09-22 17:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='15k to 1.35L Options Challenge', max_length=100)),
                ('starting_capital', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), max_digits=14)),
                ('target_profit', models.DecimalField(decimal_places=2, default=Decimal('120000.00'), max_digits=14)),
                ('target_capital', models.DecimalField(decimal_places=2, default=Decimal('135000.00'), max_digits=14)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('starting_capital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ending_capital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gross_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('trade_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('loss_count', models.IntegerField(default=0)),
                ('drawdown', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='challenge.challengeconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user', 'challenge', 'date')},
            },
        ),
    ]
