# Generated by Django 5.2.16 on 2026-09-22 17:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('entry_conditions', models.TextField(blank=True, default='')),
                ('stop_loss_rules', models.TextField(blank=True, default='')),
                ('target_rules', models.TextField(blank=True, default='')),
                ('min_rr', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('applicable_index', models.CharField(choices=[('ALL', 'All Indices'), ('NIFTY', 'NIFTY 50'), ('BANKNIFTY', 'BANKNIFTY'), ('SENSEX', 'SENSEX')], default='ALL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
