# Generated by Django 5.2.16 on 2026-09-22 17:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentLotSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(choices=[('NIFTY', 'NIFTY 50'), ('BANKNIFTY', 'BANKNIFTY'), ('SENSEX', 'SENSEX'), ('FINNIFTY', 'FINNIFTY'), ('MIDCPNIFTY', 'MIDCPNIFTY')], db_index=True, max_length=20)),
                ('lot_size', models.IntegerField(help_text='Exchange contract lot size')),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['index', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='GlobalRiskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_per_trade_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Default 1%', max_digits=5)),
                ('max_daily_loss_pct', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Default 2%', max_digits=5)),
                ('max_consecutive_losses', models.IntegerField(default=2, help_text='Max consecutive losses before cooldown')),
                ('max_trades_per_day', models.IntegerField(default=3, help_text='Default 3 trades')),
                ('min_rr_ratio', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Default 1:2', max_digits=5)),
                ('max_drawdown_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Max challenge drawdown %', max_digits=5)),
                ('is_firewall_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndexRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(choices=[('NIFTY', 'NIFTY 50'), ('BANKNIFTY', 'BANKNIFTY'), ('SENSEX', 'SENSEX')], max_length=20)),
                ('risk_per_trade_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('max_daily_loss_pct', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('max_trades', models.IntegerField(default=3)),
                ('min_rr', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('preferred_setups', models.CharField(blank=True, default='VWAP Rejection, ORB', max_length=255)),
                ('trading_session_start', models.TimeField(default='09:15:00')),
                ('trading_session_end', models.TimeField(default='15:15:00')),
                ('max_position_lots', models.IntegerField(default=4, help_text='Max allowable lots in single trade')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_risk_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'index')},
            },
        ),
    ]
