# Generated by Django 5.2.16 on 2026-09-22 17:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('dhan_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('dhan_trade_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('time', models.TimeField(default='09:20:00')),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('index', models.CharField(choices=[('NIFTY', 'NIFTY 50'), ('BANKNIFTY', 'BANKNIFTY'), ('SENSEX', 'SENSEX'), ('FINNIFTY', 'FINNIFTY'), ('MIDCPNIFTY', 'MIDCPNIFTY')], default='NIFTY', max_length=20)),
                ('symbol', models.CharField(help_text='e.g. NIFTY 24500 CE', max_length=100)),
                ('security_id', models.CharField(blank=True, default='', max_length=50)),
                ('instrument', models.CharField(choices=[('OPTION', 'Option'), ('FUTURE', 'Future'), ('EQUITY', 'Equity')], default='OPTION', max_length=20)),
                ('option_type', models.CharField(choices=[('CE', 'Call Option (CE)'), ('PE', 'Put Option (PE)'), ('NONE', 'Not Applicable')], default='CE', max_length=10)),
                ('strike', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=10)),
                ('quantity', models.IntegerField(default=25)),
                ('entry_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('broker_reported_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('risk_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rr_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('holding_time_minutes', models.IntegerField(default=0)),
                ('entry_reason', models.TextField(blank=True, default='')),
                ('exit_reason', models.TextField(blank=True, default='')),
                ('psychology', models.CharField(choices=[('CALM', 'Calm'), ('CONFIDENT', 'Confident'), ('FEAR', 'Fear'), ('GREED', 'Greed'), ('FOMO', 'FOMO'), ('REVENGE', 'Revenge'), ('UNCERTAIN', 'Uncertain')], default='CALM', max_length=20)),
                ('emotion', models.CharField(blank=True, default='Disciplined', max_length=50)),
                ('rule_followed', models.BooleanField(default=True)),
                ('mistake', models.CharField(choices=[('NONE', 'None'), ('EARLY_ENTRY', 'Early entry'), ('LATE_ENTRY', 'Late entry'), ('EARLY_EXIT', 'Early exit'), ('LATE_EXIT', 'Late exit'), ('REVENGE_TRADE', 'Revenge trade'), ('OVERTRADING', 'Overtrading'), ('INCREASED_QUANTITY', 'Increased quantity after loss'), ('IGNORED_SL', 'Ignored SL'), ('IGNORED_PLAN', 'Ignored plan')], default='NONE', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('screenshot_url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='CLOSED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='setups.setup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time', '-id'],
            },
        ),
    ]
