# Generated by Django 5.2.16 on 2026-09-22 17:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTradingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('starting_capital', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), max_digits=14)),
                ('daily_profit_target', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=14)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, default=Decimal('600.00'), max_digits=14)),
                ('max_trades', models.IntegerField(default=3)),
                ('risk_per_trade_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('max_risk_amount', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=14)),
                ('primary_index', models.CharField(default='NIFTY', max_length=20)),
                ('secondary_index', models.CharField(blank=True, default='BANKNIFTY', max_length=20)),
                ('preferred_setups', models.CharField(blank=True, default='VWAP Rejection, ORB', max_length=255)),
                ('avoid_conditions', models.TextField(blank=True, default='Choppy first 15 mins, Major RBI press conference')),
                ('market_bias', models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('NEUTRAL', 'Neutral / Rangebound'), ('VOLATILE', 'Volatile / Both Sides')], default='NEUTRAL', max_length=20)),
                ('important_events', models.TextField(blank=True, default='US CPI Data, Weekly Expiry')),
                ('notes', models.TextField(blank=True, default='')),
                ('plan_followed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
